defaults:
  - base

micro_batch_size_per_gpu: 2
ppo_mini_batch_size: 64

data:
  max_prompt_length: 5120
  max_response_length: 512

actor_rollout_ref:
  model:
    path: ${model_path}
  rollout:
    max_model_len: 5120
    response_length: 512
 
trainer:
  experiment_name: hybtqa
  total_training_steps: 1000
  save_freq: 1000
  default_local_dir: /root/autodl-tmp/ckpts

agent_proxy:
  max_turn: 8
  max_actions_per_turn: 1 # how many actions can be output at most in a single turn

es_manager:
  train:
    env_groups: 16
    group_size: 8
    env_configs:
      tags: ["HybTQA"]
      n_groups: [16]